[package]
name = "libsrt-sys"
version = "1.5.1"
authors = ["Hieu Nguyen <nthieu173@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Bindings for libsrt"
links = "srt"
build = "build.rs"
repository = "https://github.com/nthieu173/srt-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
link-cplusplus = "1.0"
openssl-sys = "0.7"

[build-dependencies]
cmake = "0.1"
bindgen = "0.56"

[features]
static = []
